# Generated by Django 5.2.6 on 2025-09-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_category_tag_alter_post_image_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='posts/placeholder.png', null=True, upload_to='posts/'),
        ),
    ]
